//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ass2mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cake
    {
        public Cake()
        {
            this.Userinfoes = new HashSet<Userinfo>();
        }
    
        public int CakeID { get; set; }
        public string CakeName { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<double> Price { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Userinfo> Userinfoes { get; set; }
    }
}
