//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ass2mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userinfo
    {
        public int ID { get; set; }
        public Nullable<int> CakeID { get; set; }
        public string Name { get; set; }
        public string Mailbox { get; set; }
        public string Profession { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Password { get; set; }
    
        public virtual Cake Cake { get; set; }
    }
}
